### ISSUE TITLE
highlight links

### ISSUE THREAD

**Issue by titaniumbones** [melioratus/org-mode#11]
in Emacs, links collapse so that they render a lot like rxegfulsr `<a href=>` links in an html page.  That might not be the right approach for Atom, but color-coding of link target and link text would still be really helpful.  Something like the wayhttps://hackmd.io highlights markdown links, maybe?

It will be so great if you're able to doa rich set of org features in Atom!

**Comment by melioratus** [comment]
@titaniumbones 

I just added syntax highlighting to Links in Atom org-mode package version in v0.3.13. Please upgrade to version v0.3.13 to see if the new syntax highlighting helps.
I'm still working on making the links collapse like in emacs. 

Thanks for your help.

Brian K ~ @melioratus

**Comment by MarcusE1W** [comment]
highlighting for links works for me :-)
Thanks for the work

**Comment by melioratus** [comment]
@titaniumbones 

In release v0.3.14, I updated the grammar for regular link objects to hide the url and square brackets when the optional description text exists.

If you would like to display the hidden parts again please add the following css to the [`styles.less`](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file.
``` css
.syntax--display-none {
  display: contents;
}
```
Thanks for your Help!

Brian K ~ @melioratus
