### ISSUE TITLE
Tilde character breaks all syntax highlighting until another Tilde character appears

### ISSUE THREAD

**Issue by aeromorrison** [melioratus/org-mode#12]
I have a large org-mode file that I use as a logbook for various IT support issues. It includes quite a few URLs within some of the nodes. Some URLs contain a ~ character. Each time there is a ~, all of the syntax highlighting is disrupted until another ~ occurs. This is sometimes hundreds of lines further down in the file and makes this part very difficult to see.

**Comment by melioratus** [comment]
I just added Link syntax to the Atom org-mode package grammar in v0.3.13 . Please update to v0.3.13 or later to see if the `~` issue is resolved.
Thank you for your help.
Brian K ~ @melioratus

**Comment by melioratus** [comment]
@aeromorrison -  I am marking this issue as closed.  If upgrading to version v0.3.13 or higher did not resolve the tilde formatting problem, please reply with a syntax example and I will re-open the ticket. Thanks again for your help!

Brian K ~ @melioratus

**Comment by aeromorrison** [comment]
Greetings. I have now had a chance to test it. It looks like a tilde character that appears in a URL is now handled properly. However, there are still issues with tilde that occur in other places.

I've attached a sample file that shows a couple of examples. It seems to make a difference if the tilde has a leading space or not. I've included both in the sample syntax below. These are representative of text that I have in several of the large org-mode files I work with regularly.

* Lorem Ipsum
- "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
- "There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
** Lorem Ipsuem Secon
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus elit leo, laoreet id elit quis, molestie gravida libero. Etiam non lacus at nibh iaculis tristique. Cras sagittis aliquam nisi eget ultricies. Nam pellentesque nunc et mi pharetra, a interdum ~sapien congue. Quisque feugiat pharetra sem sit amet commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus maximus posuere erat, in suscipit urna semper et. Aliquam erat volutpat. Praesent lobortis ~ ante ut leo~ pretium, nec luctus erat ultricies. Aliquam congue sollicitudin augue, nec vehicula nisi cursus et. Aliquam a purus egestas leo imperdiet blandit nec eget diam.

Donec finibus luctus lobortis. Aenean ~fermentum magna vitae felis mattis, sed laoreet velit commodo. Aenean tristique mi a sapien euismod aliquam. Morbi eleifend aliquam lectus fermentum vestibulum. Cras vestibulum semper nibh, quis pharetra nisl luctus et. Nullam convallis turpis nisi, at maximus augue tempor sit amet. Sed volutpat finibus finibus. Integer sit amet eros nunc. Proin molestie auctor libero eu iaculis.

Vivamus dignissim~ feugiat quam nec pharetra. Maecenas rutrum malesuada eros, sit amet volutpat arcu faucibus sit amet. Aenean commodo purus sit amet elit consectetur, a efficitur sapien euismod. Morbi eu dolor quam. Cras non turpis accumsan, sagittis enim nec, dapibus quam. Vivamus a tempus dolor, pulvinar bibendum leo. Nulla facilisi.

**Comment by melioratus** [comment]
@aeromorrison 

Thanks for the following up! I'm opening the issue again.

**Comment by melioratus** [comment]
@aeromorrison - I am marking this issue as closed (again :smile_cat:) . If upgrading to version v0.3.15 or higher does not resolve the tilde formatting problem, please reply with a syntax example and I will re-open the ticket. Thanks again for your help!

Brian K ~ @melioratus

**Comment by aeromorrison** [comment]
So far I haven't seen any formatting issues with the latest version. I'll let you know as I continue to use it if I see anything. Thanks!
