### ISSUE TITLE
how do activate?

### ISSUE THREAD

**Issue by el3ctron** [melioratus/org-mode#16]
hi, i am a atom newbie, when i open a *.org file on atom editor displays like a plane text file, my question is, i want to activate this package, or view my file with normal org mode display, how do i do this?

**Comment by melioratus** [comment]
@el3ctron - Thank you for asking your question. I am also an Atom newbie and this is my first Atom package. The org-mode package should be activated automatically whenever you open a text file with the .org file extension. If the package is activated, you should see the words “Org-Mode Syntax” in the status bar near the bottom right corner of your screen. 

When the org-mode package is activated, the syntax coloring in the file should be updated. 

As part of the package installation files, I included a sample directory which contains the org syntax files I use for testing. Please open these samples in Atom and check the status bar for the words “Org-Mode Syntax” near the bottom right corner of your screen. 

If you do not see the words “Org-Mode Syntax”, then another package could be overriding file extension mapping. 

Please reply with your findings. 

Thanks 

@melioratus

**Comment by melioratus** [comment]
- Updating the issue status to closed.
- If the issue is not resolved, I will open again.
~ Melioratus
