### ISSUE TITLE
struggle to upgrade

### ISSUE THREAD

**Issue by MarcusE1W** [melioratus/org-mode#4]
Hi.

The upgrade does not work for me. I also tried to uninstall, reinstall.

The error message is:
```
(node:1789) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.


npm WARN deprecated coffee-script@1.7.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code E404
npm ERR! 404 Not Found: underscorn-plus@^1.0.6
```

atom version 1.24
npm version: 5.6.0

**Comment by melioratus** [comment]
@MarcusE1W - Thank you for bringing this to my attention! 
I’ll update the dependencies and republish!

**Comment by melioratus** [comment]
I just pushed fix in v.0.3.11. 
Thanks again for submitting this issue!

**Comment by MarcusE1W** [comment]
Works now. Thanks.
